language: node_js
node_js:
  - "0.10.37"
before_install:
  - "exportDISPLAY=:99.0"
  - "sh-e/etc/init.d/xvfbstart"
  - "npm install -g eslint webpack eslint-plugin-react"
script:
  - "gulp check"
  - "gulp test:server"
  - "gulp test:acceptance"
addons:
  firefox: "36.0.1"
